Avoid calling vi.mock() in skipped tests
The incomplete mocks were overriding the complete mock, causing the
error: No "useIsLightBackground" export is defined on the  "../../../hooks" mock